Enumerables
imhilla/enumerable pull request #1
Opened 2020-05-15 13:37 UTC by imhilla

2020-05-16 08:30 UTC, Forison requested changes
## Status => Require changes❌
# 🙋‍♂️ Hillary,
You have done a good job so far. Here are a few changes we have to make to get this project approved😎 .
> This looks like a re-review from my dashboard. Please do not open a pull request for a re-review unless you did not follow the required Gitflow.
* [ ] Kindly add how to set up and use the project on a local machine in the readme file.
* [ ] Kindly place your test examples in a separate file.
* [ ] Check below comments for other changes you have to equally address
## That is it kindly make these changes and submit the project for re-review🤗.
Happy coding
Addo

2020-05-16 08:30 UTC, Forison commented on enumerables.rb
> +  def my_each
* [ ] There should be a working `my_each`  identical and returns the same thing as ruby's [`each`](https://ruby-doc.org/core-2.6.4/Array.html#method-i-each). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_each.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))

### replace ```my_each``` with ```each``` and compare results in the example below.

```p [1,2,3,4,5].my_each{ |a| a}```

2020-05-16 08:30 UTC, Forison commented on enumerables.rb
> +    return to_enum(:my_each_with_index) unless block_given?
* [ ] There should be a working `my_each_with_index` identical and returns the same thing as ruby's [`each_with_index`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-each_with_index). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_each_with_index.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))

### replace ```my_each_with_index``` with ```each_with_index``` and compare results in the example below.
``` p [1,2,3,4,5].my_each_with_index{ |a,b| b} ```

2020-05-18 18:17 UTC, nikasulo requested changes
# Great job! @imhilla 
Please check on this in a few minutes for some feedback!

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-05-18 18:25 UTC, nikasulo requested changes
# Great work @imhilla 
Please consider my comments below, make the necessary changes and request a re-review! 

#### my_map
Please consider the screenshot below. `my_map` should execute only the proc when a proc and block are given! Please correct this and make another review request! I wish you the very best and see you at the top :rocket: 
![screenshot](https://images2.imgbox.com/9f/b6/vBApWphz_o.png)

#### Stickler errors
You have done very nicely by including stickler in your project as requested! However, you need to ensure that all errors it throws are appropriately addressed before you request a PR review. Please look into this, address appropriately, and request another review. 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-05-18 19:46 UTC, kobiyoyo approved these changes
# Project Approved :thumbsup:
## Hello @imhilla ,  You have done a great job with this project. :clap:
#### You can go ahead and merge !!!

2020-05-19 03:30 UTC, merged